apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dep
  labels:
    app: httpd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    app: httpd-service
spec:
  externalIPs:
  - 192.168.1.40
  externalName: centos7-slave.devops.local.com
  ports:
  - name: httpd-service
    port: 80
    protocol: "TCP"
    targetPort: 80
  selector:
    app: httpd
  type: NodePort
...
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpd-ingress
  labels:
    app: httpd-ingress
spec:
  rules:
  - host: centos7-slave.devops.local.com
    http:
      paths:
      - backend:
          serviceName: httpd-service
          servicePort: 80
        path: /
